name: ruff

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
